version: '3.9'

services:
  pg-admin: 
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - "5050:80"
    restart: always

  core-backend:
    image: 310-demo:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  rabbitMQ:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
